### ISSUE TITLE
Unable to use the pay option to retrieve HNT from ledger wallet

### ISSUE THREAD

**Issue by jackoat** [helium/helium-ledger-app#14]
I have tried 3 times to move HNT out of my ledger wallet following the instructions. The first few times I thought maybe it was failing because the amount I was trying to pay had a decimal so today I tried without a decimal. I get a hash from the transaction but it never shows on the blockchain and I don't receive an error or a confirmation and the HNT remains in the wallet. I thought it was because I wasn't leaving the 35000 DC in the wallet to pay for the transaction so I left enough HNT to cover the 35000 DC, I get a hash and again the HNT doesn't move from the Ledger wallet to the payor wallet. I would like to know if I am doing something wrong or if the app is just failing to connect to the blockchain. I am able to send HNT from my Helium wallet app to the Ledger wallet. I just can't take it out of the Helium Ledger app.

**Comment by lthiery** [comment]
@jackoat does the transaction show up when you visit the pending_transactions endpoint of the API?

Just go to:

https://api.helium.io/v1/pending_transactions/$TXN_HASH

Where $TXN_HASH is the hash output by the CLI.

**Comment by jackoat** [comment]
The app is working fine the actual issue is to provide more clear instructions concerning the amount of HNT to leave in the account which is necessary for the transaction fee and potentially have that shown prior to running the pay command.
