### ISSUE TITLE
Documentation link leads to a 404

### ISSUE THREAD

**Issue by logeyG** [helium/helium-ledger-app#15]
Hey all, thanks for the development efforts for this app. It appears https://docs.helium.com/blockchain/ledger-hardware-wallet was removed recently? I want to pay using the app but can't find any explicit instructions.

**Comment by logeyG** [comment]
Used the cached google link to find the instructions. Although this is probably still an open issue generally.

**Comment by lthiery** [comment]
Thanks for logging the issue. The docs have been ported to our new site!
