### ISSUE TITLE
Provide support for validator node owner wallets

### ISSUE THREAD

**Issue by jdgemm** [helium/helium-ledger-app#18]

**Comment by ericjohncarlson** [comment]
Leaving a comment in support of this requirement.  With the growth of HNT, as well as the amount of HNT being staked for a validator, utilizing a Ledger backed wallet for this purpose would be much appreciated.

**Comment by OrmEmbaar** [comment]
I wish to also voice my support for this feature.

**Comment by lthiery** [comment]
Resolved in a57a09f7fdbc51e9c5147cd01dbb10e2970cffb5
