### ISSUE TITLE
Unable to send payment to Helium Wallet

### ISSUE THREAD

**Issue by KB3ZWI** [helium/helium-ledger-app#19]
I needed assistance with making payments. 

When I run helium-ledger-app /balance I see that I have a balance on my Ledger Nano S, as expected. When I try to pay one of my Helium wallets, I confirm the transaction on the Ledger device, and get the confirmation from the Helium Ledger App, but I never see my coins deposited and the balance on my Ledger device never changes.

**Comment by lthiery** [comment]
Did you leave enough HNT behind to pay for the transaction fee? It needs to be 0.35$ worth of HNT at least. Rate is determined by the oracle price

**Comment by KB3ZWI** [comment]
That was it. I apologize for that oversight.
