### ISSUE TITLE
What is the rational for diverging from the usual format for path derivation?

### ISSUE THREAD

**Issue by loupiote** [helium/helium-ledger-app#24]
Why does Helium use the BIP44 derivation path m/44'/904'/n'/0'/0' for account #n?

(based on the comment line 70 of https://github.com/helium/helium-ledger-app/blob/master/src/helium.c)

To conform to the use of most other cryptos, it should rather be m/44'/904'/n'/0/0 .

So, what is the rational for diverging from the usual format for path derivation, that most other crypto are using?

**Comment by lthiery** [comment]
Good question. I derived the app from [the sia example that Ledger shares](https://github.com/LedgerHQ/app-sia/blob/master/src/sia.c#L12) and it appears I inherited this comment.

After doing some reading, afaik BIP32 paths only have depth 3. I am not sure if those last two depths can be changed without upsetting the Ledger and, in fact, we don't change them, so if they are hardened are not (as indicated by the apostrophe notation) is quite irrelevant. 

So the comment should read `bip32 path for 44'/904'/n' where n in the index of the slot used`. I've cleared this up in a pending PR to avoid future confusion.

**Comment by loupiote** [comment]
> I am not sure if those last two depths can be changed without upsetting the Ledger and, in fact, we don't change them, so if they are hardened or not (as indicated by the apostrophe notation) is quite irrelevant.

The last 2 depth, if used, should not be hardened.

To be clear, can you confirm that the derivation path that you use is m/44'/904'/n'?  Or is it m/44'/904'/n'/0/0 ?

Most cryptos use a BIT32 derivation path that include the last two element (/0/0). Even though they are not useful, they are used.

So when you write:  "I am not sure if those last two depths can be changed without upsetting the Ledger", do you mean that you use them? I.e. you use the path m/44'/904'/n'/0/0 ?

It would not upset the ledger to use a different path, but it would most certainly upset the users to not get access to their accounts, since the CLI app does not have any option to set the derivation path of the account.

**Comment by lthiery** [comment]
> The last 2 depth, if used, should not be hardened.

I'm a little confused by the verbs used here. It is my understanding that the last two layers simply "are not hardened" if used. The apostrophe is simply notation of what the properties are for each layer. I can't choose to harden the paths; it's a property of the key generation at that layer. The `m/44'/904'/n'/0'/0'` you cited in your original issue is nothing other than a mistake in notation, which claims that the last two layers of bip32 are hardened when they are in fact not.

> To be clear, can you confirm that the derivation path that you use is m/44'/904'/n'? Or is it m/44'/904'/n'/0/0 

If you look at the line of code right after [your original citation](https://github.com/helium/helium-ledger-app/blob/master/src/helium.c#L71), you can see precisely what was done to derive the BIP32 path:

```
uint32_t bip32Path[] = {44 | 0x80000000, 904 | 0x80000000, index | 0x80000000, 0x80000000, 0x80000000};
```

To be explicit, this is: `m/44'/904'/n'/0/0`. I am no expert in bip32 notation, but I would expect the notation `m/44'/904'/n'/0/0` is equivalent to `m/44'/904'/n'`?

> So when you write: "I am not sure if those last two depths can be changed without upsetting the Ledger", do you mean that you use them? I.e. you use the path m/44'/904'/n'/0/0 , (contrary to your comment above) right ?

No, I don't use them which is precisely why I'm not sure what happens if you change the last two depths from `0/0`. BOLOS may cause a hard fault. There are use cases to use the non-hardened layers, so maybe it doesn't. Either way, I haven't tested this so I don't know.

> It would not upset the ledger to use a different path, but it would most certainly upset the users to not get access to their already used accounts, since the CLI app currently does not have any option to set the derivation path of the account.

This is in fact impossible to do for _any_ BOLOS application. The BOLOS environment does not allow applications to use derivations paths other than their registered path from the top two layers. That will cause a hard fault. You have to recompile the app that is loaded onto the Ledger to hope to change the derivation path at the top two layers.

While the Helium app is not in Ledger Live yet, the application has been reviewed by Ledger. They compiled it, signed it, and loaded it into their store. The only thing that is "developer mode" about it is that you have to use our CLI companion app since it is not hosted in Ledger Live.

**Comment by loupiote** [comment]
The code:

uint32_t bip32Path[] = {44 | 0x80000000, 904 | 0x80000000, index | 0x80000000, 0x80000000, 0x80000000};

indicates that the last 2 derivations are hardened (0x80000000 is the flag indicati9ng "hardened"), which is why i am worried.

The correct code should be:

uint32_t bip32Path[] = {44 | 0x80000000, 904 | 0x80000000, index | 0x80000000, 0x00000000, 0x00000000};

> No, I don't use them which is precisely why I'm not sure what happens if you change the last two depths from 0/0. BOLOS may cause a hard fault. 

BOLOS works with up to 10 derivation elements in the path ( @btchip can confirm), so it does not hard fault.  And BOLOS does not enforce any rule, i.e. any derivation that is syntactically correct will be performed.

> This is in fact impossible to do for any BOLOS application. The BOLOS environment does not allow applications to use derivations paths other than their registered path from the top two layers. 

This is incorrect. For example, in the case of ETH, the BOLOS Ethereum app allows a number of derivation path to be used, including those used by legacy accounts ( m/44'/60'/0'/n ) and those used by ledger Live accounts ( m/44'/60'/n'/0/0 ). The BOLOS environment, AKAIK, does not enforce any rules regarding derivation path. Any enforcement must be done at the BOLOS app level.

So I am still worried that the Helium app is using m/44'/904'/n'/0'/0' , rather than m/44'/904'/n'/0/0 (and if you copied/pasted code from SIA, then the SIA app may have a derivation bug too...).

> While the Helium app is not in Ledger Live yet, the application has been reviewed by Ledger.

This does not prove the app does not have bug.  Look at the FLOW app, that had a serious bug related to caching seed-related data and ignoring that the seed can be changed using a BIP39 passphrase, and also the FLOW app is using a completely wrong and funky derivation pass, which will cause issues in the future, since they will have to scan for existing accounts under the bogus path ever after they fix it.

**Comment by lthiery** [comment]
@loupiote okay that is very interesting about the `0x80000000` flag. I was trying to understand more about that but I didn't come across any docs explaining that. Thank you for the explanation, but do you have a source to read about this?

If this is the case, then the comment was accurate all along. I'm curious why the code beneath it was not the clarification you needed all along though? 

Finally, I don't see what the difference for the user if the last few layers are hardened or unhardened? As long as its documented appropriately (and thank you for your help in clarifying this). You call this a bug, but it's more an arbitrary choice from my understanding. Can you explain why hardened or unhardened on the last two layers is important for the user?

> This is only for the first 2 layers. But the rest of the path can be anything.

Yes, agreed on that. I was implying you can't diverge from the first two layers. I'm sure there are use-cases for allowing arbitrary derivations, but I don't think we will be supporting that in the near future. We are focusing on features that have immediate demand, such as the ability to stake and unstake validators. Arbitrary path derivations are a power-user feature, in my opinion, and I don't think we've had any requests for something like that. I would happily review and test a PR that brought in support like that, but I don't think I will be able to allocate time to it.

**Comment by loupiote** [comment]
> Can you explain why hardened or unhardened on the last two layers is important for the user?

It just diverge from the standard derivation used by most other cryptos. I don't think that diverging from an adopted use should happen unless there is a good reason for it.

> Arbitrary path derivations are a power-user feature, in my opinion, 

But they are necessary to recover access from accounts created by wallets using a different derivation path. 

That's why, for example,  all the Ethereum wallets that I know (MEW, MyCrypto, MetaMask) allow specifying custom derivation paths. Same for Electrum, Coinomi android wallet, etc.

Anyway, the derivation path that Helium uses with the ledger BIP39 seed should be well specified, and I find it worrisome that a non-standard path format is used (for no other reason that possibly copy/paste of bogus code from another app?).

**Comment by lthiery** [comment]
> Nope, but i'm sure you can google it and find tons of info.

I tried but I didn't find what I was looking for. I haven't found out any mention of the last two layers being conventionally unhardened either. I'm taking both of these claims from you at your word for now, but it still doesn't really change much from a practical perspective.

> Does not seem to be one here, other than the author of the code not being aware of the issue (and possible copy/paste of questionable code from another app?)

Yes, I copy-pasted the Sia app which Ledger points to as a good example to derive apps from... and we have actually found out that their comment was quite accurate. It's a little presumptuous of you to throw around baseless accusations of questionable quality about their app.

> Issues with derivation path often cause accounts to become inaccessible or impossible to recover a few years down the road, and this is a problem.

As long as its well specified, I haven't really understood why this is actually a problem. What would actually be a problem is changing the path mid-stream when users are already using the existing derivation.

**Comment by loupiote** [comment]
> I tried but I didn't find what I was looking for. I haven't found out any mention of the last two layers being conventionally unhardened either. 

They are un-hardened in the BIP44 specs, and most non-UTXO cryptos, even though they do not need the "change" and "address_index", use them in their derivation path, and they use non-hardened to stick to BIP44.

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

> It's a little presumptuous of you to throw around baseless accusations of questionable quality about their app.

I am gonna ask SIA devs if they have a good reason not to follow the de-facto standard used by 90+% of non-UTXO coins (i.e. non-hardened derivation for elements 4 and 5 of the path, as per BIP44). Maybe they just copied questionable code from another app?

> As long as its well specified, I haven't really understood why this is actually a problem. What would actually be a problem is changing the path mid-stream when users are already using the existing derivation.

Yes, I agree, but is this derivation path that should be used by Helium BIP39-compliant wallets specified anywhere on the Helium official documentation?
