### ISSUE TITLE
Unable to send from ledger nano s account. No error displayed but Tx AWOL

### ISSUE THREAD

**Issue by loupiote** [helium/helium-ledger-app#25]
I deposited some HNT to my ledger account.  Now I am unable to send them.  I am using the "rust" companion app.

```
$ .\helium-ledger-app.exe balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD | 0.95000000  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+
$ .\helium-ledger-app.exe pay 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 hnt 0.949
Communicating with Ledger - follow prompts on screen
Creating transaction for:
      0.94900000 HNT
        =
      94900000 Bones
Transaction fee: 35000 DC (1 DC = $.00001)
If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| Payee                                               | Amount HNT | Nonce | Hash                                        |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 | 0.94900000 | 1     | EKGhe4azQ0YKhtUZ1Z7d4Q4Pd097jmi_0L-iMzH0tvw |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
```

The Tx (approved on my ledger) was apparently never sent :frowning:
I am running the helium-ledger-app.exe on win10, and my Ledger is a Nano S with the latest Helium app installed (v1.0.0). Nano S firmware 1.6.1. Is there a way to figure out the issue, and most importantly, to recover the HNT that I transferred to my Nano S account?

**Comment by loupiote** [comment]
The message **_" If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price "_** seems to be incorrect.

Even if I try to send just 0.55 HNT, no HNT is burned to pay for the fees. The Tx just fails silently...

**Comment by abhay** [comment]
If I'm reading the issue correctly, the balance on the sender account seems to be ~0.01 HNT.

https://explorer.helium.com/accounts/13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD

**Comment by loupiote** [comment]
Yes, now I realize.

oilbird — Today at 12:31 AM
Did you realize that ONCHimoznRrv0gAv_1GSBieThKXhsDCaA4hexHtA1A4 went through?
loupiote — Today at 12:34 AM
Ok, I see now
I didn't realize because the balance  displayed by the app was still 0.95 HNT, even though a Tx was pending
So it looks like still a bug in the app: it should deduce any pending Tx from the balance
All the other cryptos that I know do that
when you have a pending Tx, the amount of the Tx is deduced from the account balance. and it is put back the the Tx fails
Also, it is no frustrating that the Tx fails silently, and unless the user knows hot to use the API REST endpoint, there is no way they can know about the failure
But I guess we are eating "dog food" i.e. using a very alpha version of the Helium ledger app.  And there is not even any single Helium wallet that can be used to recover access to the accounts from the BIP39 seed :frowning:

**Comment by loupiote** [comment]
Here are the chronological commands from my terminal:

...
$ .\helium-ledger-app.exe balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD | 0.95000000  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+
$ .\helium-ledger-app.exe pay 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 hnt 0.95
Communicating with Ledger - follow prompts on screen
Creating transaction for:
      0.95000000 HNT
        =
      95000000 Bones
Transaction fee: 35000 DC (1 DC = $.00001)
If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| Payee                                               | Amount HNT | Nonce | Hash                                        |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 | 0.95000000 | 1     | P_hXhJY0W4UduOOcVcvC6JFG_dS4Dtj3OWud_sdijoE |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
PS C:\Users\Tristan\Downloads\helium-ledger-app-1.1.2-x86_64-pc-windows-gnu\helium-ledger-app-1.1.2-x86_64-pc-windows-gnu> .\helium-ledger-app.exe balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD | 0.95000000  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+
$ .\helium-ledger-app.exe pay 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 hnt 0.949
Communicating with Ledger - follow prompts on screen
Creating transaction for:
      0.94900000 HNT
        =
      94900000 Bones
Transaction fee: 35000 DC (1 DC = $.00001)
If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| Payee                                               | Amount HNT | Nonce | Hash                                        |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 | 0.94900000 | 1     | EKGhe4azQ0YKhtUZ1Z7d4Q4Pd097jmi_0L-iMzH0tvw |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
$ .\helium-ledger-app.exe balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD | 0.95000000  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+
$ .\helium-ledger-app.exe pay 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 hnt 0.915
Communicating with Ledger - follow prompts on screen
Creating transaction for:
      0.91500000 HNT
        =
      91500000 Bones
Transaction fee: 35000 DC (1 DC = $.00001)
If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| Payee                                               | Amount HNT | Nonce | Hash                                        |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 | 0.91500000 | 1     | ONCHimoznRrv0gAv_1GSBieThKXhsDCaA4hexHtA1A4 |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
$ .\helium-ledger-app.exe balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD | 0.95000000  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+
$ .\helium-ledger-app.exe pay 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 hnt 0.55
Communicating with Ledger - follow prompts on screen
Creating transaction for:
      0.55000000 HNT
        =
      55000000 Bones
Transaction fee: 35000 DC (1 DC = $.00001)
If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| Payee                                               | Amount HNT | Nonce | Hash                                        |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 | 0.55000000 | 2     | v6jKOImxjvg4t9mSVtMIAnwL75fTw2NhJFbsYkxR_Ok |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
PS C:\Users\Tristan\Downloads\helium-ledger-app-1.1.2-x86_64-pc-windows-gnu\helium-ledger-app-1.1.2-x86_64-pc-windows-gnu> .\helium-ledger-app.exe balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD | 0.95000000  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+
$ .\helium-ledger-app.exe pay 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 hnt 0.6
Communicating with Ledger - follow prompts on screen
Creating transaction for:
      0.60000000 HNT
        =
      60000000 Bones
Transaction fee: 35000 DC (1 DC = $.00001)
If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| Payee                                               | Amount HNT | Nonce | Hash                                        |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| 13hJHN2vCFaawVadyJGXgFk82AG4ovtqmZkvBsLcPLUuEpFS462 | 0.60000000 | 3     | GlubZcwmczDCqwFSXyeqGhX9wC_jD5hepnwbjUgyTnw |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
$ .\helium-ledger-app.exe balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD | 0.95000000  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+
$ .\helium-ledger-app.exe balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 13H8CerbqMsGkZpnbBeEsHtEp9A4ovExpK643PNpBg5gCUzy6XD | 0.01425507  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+
$
...

**Comment by loupiote** [comment]
So the fact that the balance is incorrect (i.e. ignores any pending Tx) makes this very confusing.

**Comment by lthiery** [comment]
@loupiote thanks for the feedback!

> So it looks like still a bug in the app: it should deduce any pending Tx from the balance

I'll file a feature request against our API for this. Unsure if it fits their current model for doing things, but it certainly seems nice from a user perspective.

> Also, it is no frustrating that the Tx fails silently, and unless the user knows hot to use the API REST endpoint, there is no way they can know about the failure

I'm working on the ledger app this week and I think I'll think about ways to improve on this. At the very least, outputting the URL seems appropriate.

I'm going to close this issue for now in favor of more targeted "feature request" issues
