### ISSUE TITLE
Support for libssl 1.1?

### ISSUE THREAD

**Issue by mfalkvidd** [helium/helium-ledger-app#28]
Ubuntu 20.04 LTS ships with libssl1.1. The current release requires libssl1.0. Would it be easy to supply a release that supports libssl1.1?

**Comment by lthiery** [comment]
@mfalkvidd I've made a big update to the companion app that should enable this, as we've removed the OpenSSL dependency in favor of rustls. I need to test it on Windows as the changes were significant, but pending that, I think it's basically done on the master branch here.

**Comment by lthiery** [comment]
@mfalkvidd release v1.1.3 resolved this, right?

**Comment by mfalkvidd** [comment]
I think so but I can verify tomorrow and report back.

**Comment by mfalkvidd** [comment]
Sorry, I can't find the v1.1.3 release so I can't verify. Where can I find the release?

**Comment by lthiery** [comment]
I've moved the CLI companion app to another repo: https://github.com/helium/helium-ledger-cli
