### ISSUE TITLE
Sent HNT to new address on Ledger and it's not showing on explorer and never received.

### ISSUE THREAD

**Issue by trstaub** [helium/helium-ledger-app#32]
I actually need help recovering the transaction to actually receive the helium.  I never received the transaction.

Sending/withdrawing from Binance.us > receiving/depositing to my Ledger Nano S
Ledger Nano S Firmware 1.6.1
Ledger Live 2.26.1
Helium Account loaded on Ledger ver 1.0 with Developer mode enabled
Windows CLI Helium Ledger App 1.1.2

Followed instructions here without issue: https://docs.helium.com/wallets/ledger/
displays my address OK
sending to that address does not receive anything and does not show in Helium Explorer

I actually need help recovering the transaction to actually receive the helium.

**Comment by lthiery** [comment]
I'm going to need more information to try to help.

What was the transaction hash? Whats the wallet address?

**Comment by trstaub** [comment]
Hi,
Thank you.
I replied directly to your Helium email address with screenshots.
Thank you in advance for your time and assistance.

**Comment by lthiery** [comment]
Based on our discussions, this seems to be a problem related to Binanace.US submitting the transaction properly and unrelated to the Ledger wallet.
