### ISSUE TITLE
"--new/old-address" is confusing since both validators and owners are addresses

### ISSUE THREAD

**Issue by jamiew** [helium/helium-ledger-app#46]
I think using `--new-validator` and `--old-validator` might be more clear

**Comment by lthiery** [comment]
I don't disagree but we will want to raise this with @madninja too. I've kept the ledger-app consistent with the UX of helium-wallet as much as possible and if I make the change here we probably want to carry it over to helum-wallet too:

https://github.com/helium/helium-wallet-rs/blob/master/src/cmd/validators/transfer.rs#L19

I think the logic on @madninja 's side has been to maintain the variables defined in the protobufs:

https://github.com/helium/proto/blob/master/src/blockchain_txn_transfer_validator_stake_v1.proto#L5

**Comment by jamiew** [comment]
Maybe allow for both but have docs use `--new-validator`? Don't love that solution either

**Comment by lthiery** [comment]
Yea that approach sounds like a half measure to me. 

IMO, if we think it’s a worthwhile change, we break the interface but should maintain consistency with wallet.

**Comment by jamiew** [comment]
I don't disagree. Feel free to close as #willnotfix. May god have mercy on
our souls

**Comment by lthiery** [comment]
#willnotfix :P
