### ISSUE TITLE
add burn transaction to ledger cli

### ISSUE THREAD

**Issue by cokes518** [helium/helium-ledger-app#50]
in order to participate in helium vote, users must submit a burn transaction to a designated address for their vote to count. This isn't an issue with the app or CLI, but for users with their HNT in a ledger wallet, this is impossible.

**Comment by janhartje** [comment]
Isn't that already possible? At least I can burn to an address of my choice.

**Comment by lthiery** [comment]
Yes, this is complete. Thanks for mentioning it!
