### ISSUE TITLE
How can I vote using Ledger on Windows?

### ISSUE THREAD

**Issue by jackz12345** [helium/helium-ledger-app#52]
If I want to vote for HIPS I must burn tokens and on Helium vote it says the command is helium-wallet burn --amount 0.00000001 --payee 13pPtEyg3idu2GDeFCjbuU1uVLaZax9yBqDouPPdgsAYznq7982 --commit or helium-wallet burn --amount 0.00000001 --payee 13qVx7MRzocyKZ4bW3oEkvnQrTK4DftKEcjHVYP1zhMtUhnqYye --commit.

I was wondering if this could be executed of windows CMD or a different CLI.

Thanks

**Comment by lthiery** [comment]
Sorry for the very late response. The helium.vote website now contains Ledger specific instructions. I think when you initially filed this ticket, it was perhaps not there.

![image](https://user-images.githubusercontent.com/1606640/171111352-28bf836c-19db-432b-b36d-39a3ed7c7112.png)
