### ISSUE TITLE
Newbie needs help

### ISSUE THREAD

**Issue by SpeedForceGN** [helium/helium-ledger-app#53]
I am really new to this and having a hard time getting CLI and ledger to work.  I am newbie and not great with command prompt.  I am using a Windows 10 Laptop and have a Nano X.  I am attaching a picture so that you can see where I am stuck. 
<img width="550" alt="install" src="https://user-images.githubusercontent.com/61169069/142772921-e973718d-cc07-4c05-90bf-6009827942ab.PNG">

**Comment by lthiery** [comment]
I am not sure where exactly you are stuck. Please re-open this issue and provide more precise information of what you see on your screen and what your last successful command was.
