### ISSUE TITLE
Need help with "decoding error" when attempting Pay via Helium Ledger CLI

### ISSUE THREAD

**Issue by cameronnili5** [helium/helium-ledger-app#58]
Hi all, I am receiving "error: Decoding Error" when attempting to make a payment to an HNT address via my Helium Ledger CLI. I've got it set up correctly (can pull balance info and all) but seemingly cannot make a payment. Any tips? Thanks!

**Comment by lthiery** [comment]
@cameronnili5 is it possible you have not updated to the latest version of the Ledger CLI?

**Comment by cameronnili5** [comment]
Hi, thanks for the comment! After checking, it seems that although I've installed the latest Healium Ledger CLI version (2.2.3) my CLI runs an older version when I initialize helium-ledger-cli. I'm sort of a newbie, so how do I tell the CLI to run the newer version?

**Comment by lthiery** [comment]
You probably aliased the old version or you put the directory that it lives in into your `PATH`. What OS are you on? Does `whereis helium-ledger-cli` return anything?

**Comment by cameronnili5** [comment]
`whereis helium-ledger-cli` does not return anything. You're probably right, I aliased it. How do I un-alias it? I'm on Monterey MacOS

**Comment by lthiery** [comment]
I'm not a mac user but i think aliases are in `~/.bashrc` on there too.

Also, you can always just `cd` into the directory where you unzipped the new version and just call it directly: `./helium-ledger-cli`
