### ISSUE TITLE
QNT to Nano Ledger Live Hard Wallet deposited as ETH

### ISSUE THREAD

**Issue by NdotBur** [helium/helium-ledger-app#62]
I recently transferred QNT to my Nano Ledger Live hard wallet from Uphold. Uphold stated QNT is part of the ETH network and wanted me to confirm that the transfer was still wanted. The transfer however, was deposited to my Nano as ETH. Is anyone familiar with this error and knows of a fix?

**Comment by lthiery** [comment]
This seems unrelated to HNT. You should try to get support for the ETH wallet.

**Comment by NdotBur** [comment]
Okay, thank you!
