### ISSUE TITLE
Migration HNT to Solana

### ISSUE THREAD

**Issue by sysfu** [helium/helium-ledger-app#64]
I recently tried to check my balance using the helium-ledger-app 1.1.2 and it's giving me an API error.

Is there any way that I can migrate the helium stuck on my Ledger Nano S Plus device to the Solana network?

**Comment by heliumsupports** [comment]
Have you tried to update your API Firmware ?

**Comment by sysfu** [comment]
I eventually figured out how to migrate my HNT to solana successfully but it was so long ago I forgot exactly how I did it.
