### ISSUE TITLE
Ledger is running but Helium application does not appear to be running error

### ISSUE THREAD

**Issue by evectis** [helium/helium-ledger-app#8]
After Helium App that is signed by Ledger and is trusted is installed on my ledger device, trying to follow instructions on Windows 10 to interact with the Helium App app on the Ledger device.  Get to step 4 here - https://github.com/helium/helium-ledger-app and my Nano S device disconnects from the Ledger Live app as soon as the "helium-ledger-app balance" command is executed.

**Comment by lthiery** [comment]
Hello @evectis - thank you for the report!

When you say "the Nano S disconnects from the Ledger Live app as soon as the [command] is excecuted", what do you mean exactly?

In the case of the Helium, we only use Ledger Live to install the Helium application on the Nano S. After that, you only need the command line tool to interact with the Nano S.

It may no be clear in the README, but once you've used Ledger Live to install the application, you need to:
1. start the Helium app by selecting it on the Ledger screen. The "Waiting for commands..." prompt should be on the screen.
2. execute commands

In some cases, Ledger Live might still be connected to the Nano S and might actually get in the way of the command line tool (aka companion app) from interfacing with the device. 

Please let me know if this resolves things for you and if not, give me as much detail about what's going wrong and when.

**Comment by evectis** [comment]
lthiery, thanks for the reply!
Yes, you are correct that, at least for me, it was not clear in the README that once you've used Ledger Live to install the application, you need to:
1 - start the Helium app by selecting it on the Ledger screen. The "Waiting for commands..." prompt should be on the screen.
2 - execute commands
I did figure this out on my own once I installed a different app on my Nano S and it's instructions for use did make it clear.  I was able to send HNT from my Helium device/Android app wallet to the Helium app on my Nano S.
Another question here, when will the Ledger Live Helium app be "Live supported"?
