### ISSUE TITLE
Helium app Ledger Live "Live supported"?

### ISSUE THREAD

**Issue by evectis** [helium/helium-ledger-app#9]
When will the Ledger Live Helium app be "Live supported"?

**Comment by lthiery** [comment]
Hello again @evectis and thanks for dropping a note!

To have the wallet GUI supported within Ledger Live (ie: be one of the crypto-currencies with a blue label [here](https://www.ledger.com/supported-crypto-assets/)) will take some time and collaboration with the Ledger team. As far as I understand, the Ledger team takes ownership of that process themselves and there's not much we can do there other than have interested individuals such as yourself mention your interest to them :)

What we may be doing on our end is making a GUI to wrap the CLI. But I don't have any firm dates on that at this point either.

**Comment by chrisabruce** [comment]
@lthiery would be nice to roll this into `helium-wallet-rs`.

**Comment by lthiery** [comment]
@chrisabruce 
It's what I initially tried to do but it was painful to try to build `helium-wallet-rs` for Windows. And for Ledger, you must have the "companion app" on Windows to be eligible for developer mode distribution.

That being said, maybe I can give `helium-wallet-rs` another Windows build pass with Gitub Workflows now that we've migrated. It might be easier now.

**Comment by mfalkvidd** [comment]
Basing the ledger app on helium-wallet-rs would also make it possible to transfer hotspots to the ledger wallet, right? And to use the ledger wallet to assert hotspot location.

**Comment by sabifa** [comment]
Any update on this? 👀

**Comment by lthiery** [comment]
I've added some tests and we are waiting in line for the security review. We've [prepared the JS library](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-helium) so integration might be relatively fast after security review. Hard to predict when though as I know the LedgerHQ team is very busy!

**Comment by janhartje** [comment]
Can we support somehow to achieve ledger live for helium?

**Comment by lthiery** [comment]
@janhartje We're making headway on it. The security review and the JS library are all pieces that need to be in place before Ledger will consider doing the integration into Ledger Live. With those completed, we hope it'll be ready soon! No firm timeline on it yet though.

**Comment by Deojuvente** [comment]
look like there allrdy working on it https://www.ledger.com/helium-wallet
but if you click the link notting works. :(

**Comment by Perronef5** [comment]
> look like there allrdy working on it https://www.ledger.com/helium-wallet
> 
> but if you click the link notting works. :(

Yeah I think that's because the feature is still not ready. Should be ready soon.

**Comment by ApfelBirneKreis** [comment]
Whats the status on this? is Ledger Live support coming?

**Comment by lthiery** [comment]
Hi @ApfelBirneKreis - as Helium migrates to Solana as the new L1, a standalone Ledger Live app is no longer required. All functionality will be accomplished under the Solana Ledger Live application.
